general:
  config_reload_commands: []

  startup_commands: ['shell-exec zebar']

  shutdown_commands: ['shell-exec taskkill /IM zebar.exe /F']

  focus_follows_cursor: true

  toggle_workspace_on_refocus: false

  cursor_jump:
    enabled: true
    trigger: "window_focus"

  hide_method: "cloak"

  show_all_in_taskbar: false

gaps:
  scale_with_dpi: true

  inner_gap: "10px"

  outer_gap:
    top: "50px"
    right: "20px"
    bottom: "20px"
    left: "20px"

window_effects:
  focused_window:
    border:
      enabled: true
      color: "#8dbcff"

    hide_title_bar:
      enabled: false

    corner_style:
      enabled: true
      style: "rounded"

    transparency:
      enabled: false
    opacity: "100%"

  other_windows:
    border:
      enabled: true
      color: "#a1a1a1"
    hide_title_bar:
      enabled: false
    corner_style:
      enabled: false
      style: "square"
    transparency:
      enabled: false
      opacity: "0%"

window_behavior:
  initial_state: "tiling"

  state_defaults:
    floating:
      centered: true

      shown_on_top: true

    fullscreen:
      maximized: false

      shown_on_top: true

workspaces:
  - name: "1"
    display_name: "remote"
    bind_to_monitor: 0
    keep_alive: true
  - name: "2"
    keep_alive: true
  - name: "3"
    keep_alive: true
  - name: "4"
    keep_alive: true

window_rules:
  - commands: ["ignore"]
    match:
      - window_process: { equals: 'zebar' }
      - window_process: { equals: "Calendar" }
      - window_process: { equals: "People" }
      - window_process: { equals: "Files" }
      # - window_title: { regex: '[Pp]icture.in.[Pp]icture' }
      #   window_class: { regex: 'Chrome_WidgetWin_1|MozillaDialogClass' }
      # - window_process: { equals: 'PowerToys' }
      #   window_class: { regex: 'HwndWrapper\[PowerToys\.PowerAccent.*?\]' }
      # - window_process: { equals: 'PowerToys' }
      #   window_title: { regex: '.*? - Peek' }
      # - window_process: { equals: 'Lively' }
      #   window_class: { regex: 'HwndWrapper' }
      # - window_process: { equals: 'EXCEL' }
      #   window_class: { not_regex: 'XLMAIN' }
      # - window_process: { equals: 'WINWORD' }
      #   window_class: { not_regex: 'OpusApp' }
      # - window_process: { equals: 'POWERPNT' }
      #   window_class: { not_regex: 'PPTFrameClass' }

binding_modes:
keybindings:
  - commands: ['focus --direction left']
    bindings: ['alt+a' ]
  - commands: ['focus --direction right']
    bindings: ['alt+t']
  - commands: ["toggle-fullscreen"]
    bindings: ["alt+f"]
  - commands: ["toggle-minimized"]
    bindings: ["alt+m"]
  - commands: ["close"]
    bindings: ["alt+q"]

  - commands: ['wm-toggle-pause']
    bindings: ['alt+d']


  # Change focus to a workspace defined in `workspaces` config.
  - commands: ["focus --workspace 1", "focus --workspace 1"]
    bindings: ["alt+n"]
  - commands: ["focus --workspace 2", "focus --workspace 2"]
    bindings: ["alt+e"]
  - commands: ["focus --workspace 3", "focus --workspace 3"]
    bindings: ["alt+i"]
  - commands: ["focus --workspace 4", "focus --workspace 4"]
    bindings: ["alt+l"]

  - commands: ["move --workspace 1", "focus --workspace 1"]
    bindings: ["alt+shift+n"]
  - commands: ["move --workspace 2", "focus --workspace 2"]
    bindings: ["alt+shift+e"]
  - commands: ["move --workspace 3", "focus --workspace 3"]
    bindings: ["alt+shift+i"]
  - commands: ["move --workspace 4", "focus --workspace 4"]
    bindings: ["alt+shift+l"]

  # # Move the focused window's parent workspace to a monitor in a given
  # # direction.
  # - commands: ['move-workspace --direction left']
  #   bindings: ['alt+shift+a']
  # - commands: ['move-workspace --direction right']
  #   bindings: ['alt+shift+f']
  # - commands: ['move-workspace --direction up']
  #   bindings: ['alt+shift+d']
  # - commands: ['move-workspace --direction down']
  #   bindings: ['alt+shift+s']
 
