general:
  config_reload_commands: []

  focus_follows_cursor: true

  toggle_workspace_on_refocus: false

  cursor_jump:
    enabled: true
    trigger: "window_focus"

  hide_method: "cloak"

  show_all_in_taskbar: false

gaps:
  scale_with_dpi: true

  inner_gap: "10px"

  outer_gap:
    top: "10px"
    right: "20px"
    bottom: "40px"
    left: "20px"

window_effects:
  focused_window:
    border:
      enabled: true
      color: "#8dbcff"

    hide_title_bar:
      enabled: true

    corner_style:
      enabled: true
      style: "rounded"

    transparency:
      enabled: false
    opacity: "100%"

  other_windows:
    border:
      enabled: true
      color: "#a1a1a1"
    hide_title_bar:
      enabled: false
    corner_style:
      enabled: false
      style: "square"
    transparency:
      enabled: false
      opacity: "0%"

window_behavior:
  initial_state: "tiling"

  state_defaults:
    floating:
      centered: false

      shown_on_top: false

    fullscreen:
      maximized: false

      shown_on_top: true

workspaces:
  - name: "1"
    keep_alive: true
  - name: "2"
    keep_alive: true
  - name: "3"
    keep_alive: true
  - name: "4"
    keep_alive: true
  - name: "5"
    keep_alive: true
  - name: "6"
  - name: "7"

window_rules:
  - commands: ["ignore"]
    match:
      - window_process: { equals: "Calendar" }
      - window_process: { equals: "People" }
      - window_process: { equals: "Files" }
      
      - window_title: { regex: "[Pp]icture.in.[Pp]icture" }
        window_class: { regex: "Chrome_WidgetWin_1|MozillaDialogClass" }

      - window_process: { regex: "PowerToys" }

        window_title: { regex: ".*? - Peek" }
      - window_process: { equals: "Lively" }
        window_class: { regex: "HwndWrapper" }

binding_modes:
keybindings:

  - commands: ['focus --direction left']
    bindings: ['alt+a' ]
  - commands: ['focus --direction right']
    bindings: ['alt+t']

  - commands: ["toggle-fullscreen"]
    bindings: ["alt+f"]

  - commands: ["toggle-minimized"]
    bindings: ["alt+m"]

  - commands: ["close"]
    bindings: ["alt+q"]

  # Redraw all windows.
  - commands: ["wm-redraw"]
    bindings: ["alt+r"]


  - commands: ['wm-toggle-pause']
    bindings: ['alt+d']

  # Launch CMD terminal. Alternatively, use `shell-exec wt` or
  # `shell-exec %ProgramFiles%/Git/git-bash.exe` to start Windows
  # Terminal and Git Bash respectively.
  # - commands: ["shell-exec  C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe"]
    # bindings: ["alt+enter"]

  # Change focus to a workspace defined in `workspaces` config.
  - commands: ["focus --workspace 1", "focus --workspace 1"]
    bindings: ["alt+n"]
  - commands: ["focus --workspace 2", "focus --workspace 2"]
    bindings: ["alt+e"]
  - commands: ["focus --workspace 3", "focus --workspace 3"]
    bindings: ["alt+i"]
  - commands: ["focus --workspace 4", "focus --workspace 4"]
    bindings: ["alt+l"]
  - commands: ["focus --workspace 5", "focus --workspace 5"]
    bindings: ["alt+u"]
  - commands: ["focus --workspace 6", "focus --workspace 6"]
    bindings: ["alt+y"]

  - commands: ["move --workspace 1", "focus --workspace 1"]
    bindings: ["alt+shift+n"]
  - commands: ["move --workspace 2", "focus --workspace 2"]
    bindings: ["alt+shift+e"]
  - commands: ["move --workspace 3", "focus --workspace 3"]
    bindings: ["alt+shift+i"]
  - commands: ["move --workspace 4", "focus --workspace 4"]
    bindings: ["alt+shift+l"]
  - commands: ["move --workspace 5", "focus --workspace 5"]
    bindings: ["alt+shift+u"]
  - commands: ["move --workspace 6", "focus --workspace 6"]
    bindings: ["alt+shift+y"]
