# Windows Package Installation Script

$ErrorActionPreference = "Stop"
$ProgressPreference = "SilentlyContinue"

function Write-Status($msg, $color = "Cyan") {
    Write-Host "==> $msg" -ForegroundColor $color
}

# Idempotently install a stub at the given path that sources the canonical
# ~/.config/powershell/profile.ps1. Safe to re-run; preserves anything the
# user added before the stub by appending the stub block if it isn't there.
function Install-ProfileStub {
    param(
        [Parameter(Mandatory)][string]$Path,
        [string]$Label = $Path
    )

    $marker  = "# >>> win-dot profile stub >>>"
    $endTag  = "# <<< win-dot profile stub <<<"
    $stub    = @"
$marker
# Auto-generated by scripts/install-packages.ps1. Sources the canonical
# pwsh profile so we don't have to track per-host `$PROFILE files
# (whose paths depend on OneDrive KFM, tenant name, and pwsh version).
`$localProfile = Join-Path `$HOME '.config\powershell\profile.ps1'
if (Test-Path `$localProfile) { . `$localProfile }
$endTag
"@

    $dir = Split-Path -Parent $Path
    if (-not (Test-Path $dir)) {
        New-Item -ItemType Directory -Path $dir -Force | Out-Null
    }

    if (Test-Path $Path) {
        $existing = Get-Content $Path -Raw
        # Detect either our markered stub OR a previously hand-written stub that
        # already sources the canonical profile, so we don't append duplicates.
        $hasMarker = $existing -like "*$marker*"
        $hasManualStub = $existing -match '\.config[\\/]powershell[\\/]profile\.ps1'
        if ($hasMarker -or $hasManualStub) {
            Write-Status "Profile stub already present at $Label" "Green"
            return
        }
        # Preserve pre-existing content; append the stub with a blank-line break.
        $separator = if ($existing.EndsWith("`n")) { "`n" } else { "`n`n" }
        Add-Content -Path $Path -Value "$separator$stub" -Encoding UTF8
        Write-Status "Appended profile stub to $Label" "Green"
    } else {
        Set-Content -Path $Path -Value $stub -Encoding UTF8
        Write-Status "Wrote profile stub at $Label" "Green"
    }
}

function Install-ProfileStubs {
    Write-Status "Wiring PowerShell profile stubs to ~/.config/powershell/profile.ps1..."

    # pwsh 7 — uses $PROFILE in the running pwsh.
    if (Get-Command pwsh -ErrorAction SilentlyContinue) {
        $pwsh7Profile = & pwsh -NoLogo -NoProfile -Command 'Write-Output $PROFILE.CurrentUserCurrentHost' 2>$null
        if ($pwsh7Profile) {
            Install-ProfileStub -Path $pwsh7Profile.Trim() -Label "pwsh 7 ($pwsh7Profile)"
        }
    } else {
        Write-Status "pwsh not found, skipping pwsh 7 stub" "Yellow"
    }

    # Windows PowerShell 5.1 — has its own $PROFILE under WindowsPowerShell\.
    if (Get-Command powershell -ErrorAction SilentlyContinue) {
        $ps51Profile = & powershell -NoLogo -NoProfile -Command 'Write-Output $PROFILE.CurrentUserCurrentHost' 2>$null
        if ($ps51Profile) {
            Install-ProfileStub -Path $ps51Profile.Trim() -Label "powershell 5.1 ($ps51Profile)"
        }
    } else {
        Write-Status "Windows PowerShell not found, skipping 5.1 stub" "Yellow"
    }
}

function Install-ScoopPackage($package) {
    try {
        $pkgName = $package -replace '^[^/]+/', ''
        if (scoop list $pkgName 2>$null) {
            Write-Status "$pkgName already installed" "Green"
            return $true
        }

        Write-Status "Installing $package..."
        scoop install $package *>&1 | Out-Null
        if ($LASTEXITCODE -eq 0) {
            Write-Status "Installed $package" "Green"
            return $true
        } else {
            Write-Status "Failed to install $package (exit code: $LASTEXITCODE)" "Yellow"
            return $false
        }
    }
    catch {
        Write-Status "Error installing $package`: $_" "Yellow"
        return $false
    }
}

function Install-WingetPackage($package) {
    try {
        Write-Status "Checking $package..."
        $installed = winget list --id $package --exact 2>$null
        if ($installed -match $package) {
            Write-Status "$package already installed" "Green"
            return $true
        }

        Write-Status "Installing $package..."
        winget install --id $package --source winget --accept-source-agreements --accept-package-agreements --silent
        if ($LASTEXITCODE -eq 0) {
            Write-Status "Installed $package" "Green"
            return $true
        } else {
            Write-Status "Failed to install $package (exit code: $LASTEXITCODE)" "Yellow"
            return $false
        }
    }
    catch {
        Write-Status "Error installing $package`: $_" "Yellow"
        return $false
    }
}

# Check if Scoop is installed, install if needed
if (-not (Get-Command scoop -ErrorAction SilentlyContinue)) {
    Write-Status "Installing Scoop package manager..."
    try {
        Set-ExecutionPolicy RemoteSigned -Scope CurrentUser -Force
        Invoke-WebRequest -UseBasicParsing -Uri get.scoop.sh | Invoke-Expression

        # Add Scoop to the current session path
        $env:PATH = "$env:USERPROFILE\scoop\shims;$env:PATH"

        # Verify Scoop is now available
        if (-not (Get-Command scoop -ErrorAction SilentlyContinue)) {
            throw "Scoop installation failed - command not found after install"
        }
        Write-Status "Scoop installed successfully" "Green"
    }
    catch {
        Write-Host "Failed to install Scoop: $_" -ForegroundColor Red
        exit 1
    }
} else {
    Write-Status "Scoop already installed" "Green"
}

# Scoop Packages
Write-Status "Setting up Scoop buckets..."
try {
    scoop update *>&1 | Out-Null
    scoop bucket add extras 2>$null
    scoop bucket add main 2>$null
    scoop bucket add versions 2>$null
    Write-Status "Scoop buckets configured" "Green"
}
catch {
    Write-Status "Warning: Issue configuring buckets: $_" "Yellow"
}

Write-Status "Installing Scoop packages..."
$scoopPackages = @("extras/obsidian","main/neovim","git", "nodejs-lts", "7zip", "gh", "fzf", "ripgrep", "make", "cmake", "bat", "starship", "d2")
$scoopFailed = @()
foreach ($tool in $scoopPackages) {
    if (-not (Install-ScoopPackage $tool)) {
        $scoopFailed += $tool
    }
}

# Winget Packages
Write-Host "Installing Winget packages..."
$wingetPackages = @(
    "glzr-io.glazewm",
    "glzr-io.zebar",
    "Microsoft.PowerToys",
    "Microsoft.PowerShell.Preview",
    "Microsoft.DotNet.SDK.9",
    "Microsoft.DotNet.DesktopRuntime.9",
    "Microsoft.DotNet.AspNetCore.6",
    "Microsoft.DotNet.DesktopRuntime.6",
    "Microsoft.DotNet.AspNetCore.6",
    "DEVCOM.JetBrainsMonoNerdFont",
    "Microsoft.AzureCLI",
    "aristocratos.btop4win"
)

foreach ($pkg in $wingetPackages) {
    winget install --id $pkg --source winget --accept-source-agreements --accept-package-agreements
    Write-Host "Installed $pkg."
}

# Microsoft.PowerShell.Preview's installer ships a buggy PATH entry
# (`...\7-preview\preview` — a non-existent subdir).  Add the correct dir
# to the User PATH so `pwsh` is resolvable without a logoff.
$pwshDir = "C:\Program Files\PowerShell\7-preview"
if (Test-Path (Join-Path $pwshDir 'pwsh.exe')) {
    $userPath = [Environment]::GetEnvironmentVariable('Path', 'User')
    if (($userPath -split ';') -notcontains $pwshDir) {
        $newPath = if ($userPath) { "$userPath;$pwshDir" } else { $pwshDir }
        [Environment]::SetEnvironmentVariable('Path', $newPath, 'User')
        $env:Path = "$env:Path;$pwshDir"
        Write-Host "Added '$pwshDir' to User PATH" -ForegroundColor Green
    }
}

winget install GlazeWM --source winget --accept-source-agreements --accept-package-agreements

# Azure Authentication CLI
Write-Host "Installing Azure Authentication CLI..."
$env:AZUREAUTH_VERSION = '0.9.2'
$script = "${env:TEMP}\install.ps1"
$url = "https://raw.githubusercontent.com/AzureAD/microsoft-authentication-cli/${env:AZUREAUTH_VERSION}/install/install.ps1"
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
Invoke-WebRequest $url -OutFile $script
if ($?) {
    & $script
    Write-Host "Installed Azure Authentication CLI."
}
if ($?) {
    Remove-Item $script
}

# PSMUX - tmux-compatible terminal multiplexer for Windows
Write-Host "Installing PSMUX (modern psmux 3.x with .tmux.conf support)..."
try {
    # If an old standalone install exists from earlier versions, clean it up.
    $legacyInstallDir = "$env:LOCALAPPDATA\psmux"
    if (Test-Path "$legacyInstallDir\psmux.exe") {
        $legacyVersion = (& "$legacyInstallDir\psmux.exe" version 2>&1 | Out-String)
        if ($legacyVersion -match 'psmux 0\.') {
            Write-Host "Removing legacy psmux 0.x install..." -ForegroundColor Yellow
            Get-Process -Name psmux, pmux, tmux -ErrorAction SilentlyContinue |
                ForEach-Object { Stop-Process -Id $_.Id -Force -ErrorAction SilentlyContinue }
            Remove-Item -Recurse -Force $legacyInstallDir -ErrorAction SilentlyContinue

            $userPath = [Environment]::GetEnvironmentVariable('Path', 'User')
            $cleaned = ($userPath -split ';' | Where-Object { $_ -and ($_ -notlike "*\psmux*") }) -join ';'
            [Environment]::SetEnvironmentVariable('Path', $cleaned, 'User')
            $env:Path = ($env:Path -split ';' | Where-Object { $_ -and ($_ -notlike "*\psmux*") }) -join ';'
        }
    }

    winget install --id marlocarlo.psmux --source winget `
        --accept-source-agreements --accept-package-agreements --silent
    if ($LASTEXITCODE -eq 0) {
        Write-Host "Installed PSMUX" -ForegroundColor Green
    } else {
        Write-Host "Warning: psmux install exited with code $LASTEXITCODE" -ForegroundColor Yellow
    }
}
catch {
    Write-Host "Warning: Failed to install PSMUX: $_" -ForegroundColor Yellow
}

# Setup Neovim configuration
Write-Host "Setting up Neovim configuration..."
$nvimSetupScript = Join-Path $PSScriptRoot "setup-nvim-config.ps1"
if (Test-Path $nvimSetupScript) {
    & $nvimSetupScript
} else {
    Write-Host "Warning: setup-nvim-config.ps1 not found" -ForegroundColor Yellow
}

# Azure CLI Extensions
Write-Host "Installing Azure CLI extensions..."
if (Get-Command az -ErrorAction SilentlyContinue) {
    try {
        az extension add --name azure-devops --yes 2>&1 | Out-Host
        if ($LASTEXITCODE -eq 0) {
            Write-Host "Installed Azure DevOps extension" -ForegroundColor Green
        } else {
            Write-Host "Warning: Failed to install Azure DevOps extension" -ForegroundColor Yellow
        }
    }
    catch {
        Write-Host "Warning: Error installing Azure DevOps extension: $_" -ForegroundColor Yellow
    }
} else {
    Write-Host "Azure CLI not found, skipping extension installation" -ForegroundColor Yellow
}

Write-Host "✅ Package installation complete."

# ---------------------------------------------------------------------------
# Install PowerShell profile stubs at the runtime-resolved $PROFILE paths.
# We never track $PROFILE files in the repo: their path depends on whether
# OneDrive Known Folder Move is redirecting Documents, the tenant name, and
# the PowerShell host (pwsh 7 vs Windows PowerShell 5.1). Instead, we write
# a tiny dot-source stub on each machine that points at the canonical
# ~/.config/powershell/profile.ps1, which IS tracked in this repo.
# ---------------------------------------------------------------------------
Install-ProfileStubs

